version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      dependencies:
        patterns: ['*']
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        patterns: ['*']
    labels: [dependencies]
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels: [dependencies]
