services:
  postgres:
    image: postgres:16-alpine
    container_name: gitgone_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-adonis}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-gitgone}
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
